In [ ]:
'''Step 1: Install Required Library

To work with Excel files, Pandas uses an additional package called OpenPyXL.

Install it using: cmd run as admin

pip install openpyxl'''

In [1]:
'''Step 2: Import Pandas'''

import pandas as pd

In [ ]:
'''Step 3: Read an Excel File

Suppose you have a file named:

sales.xlsx'''

In [16]:
df = pd.read_excel(r"C:\Users\amita\Desktop\sales.xlsx")
#The r makes it a raw string, so Python treats the backslashes (\) correctly.
#Replace amita with your system's username 
print(df)

   OrderID Customer  Sales
0     1001     John    500
1     1002     Mary    700
2     1003    David    400

In [28]:
'''Reading a Specific Sheet

Many Excel files contain multiple sheets.

Example:

sales.xlsx

Sheet1 = January
Sheet2 = February
Sheet3 = March'''


df = pd.read_excel(r"C:\Users\amita\Desktop\sales.xlsx", sheet_name="March")
print(df)

   OrderID Customer  Sales
0     1007    Kevin    900
1     1008    Holly    234
2     1009      Nic    253

In [30]:
# or 
df = pd.read_excel(r"C:\Users\amita\Desktop\sales.xlsx", sheet_name=0)
print(df)

   OrderID Customer  Sales
0     1001     John    500
1     1002     Mary    700
2     1003    David    400

In [35]:
#View Available Sheets

excel_file = pd.ExcelFile(r"C:\Users\amita\Desktop\sales.xlsx")

print(excel_file.sheet_names)

['January', 'February', 'March']

In [46]:
# Reading multiple sheets
# Path to Excel file
file_path = r"C:\Users\amita\Desktop\sales.xlsx"

In [47]:
# Read all sheets
all_sheets = pd.read_excel(file_path, sheet_name=None)

In [48]:
# Show sheet names
print("Available Sheets:")
print(all_sheets.keys())

Available Sheets:
dict_keys(['January', 'February', 'March'])

In [54]:
# Display first 2 rows of each sheet
for sheet_name, df in all_sheets.items():
    print("\n" + "="*50)
    print(f"Sheet: {sheet_name}")
    print("="*50)
    display(df.head(2))

==================================================
Sheet: January
==================================================

   OrderID Customer  Sales
0     1001     John    500
1     1002     Mary    700

==================================================
Sheet: February
==================================================

   OrderID Customer  Sales
0     1004    Chris   1000
1     1005    Kelly    100

==================================================
Sheet: March
==================================================

   OrderID Customer  Sales
0     1007    Kevin    900
1     1008    Holly    234

In [59]:
'''Example 2: Read Specific Sheets by Name

Suppose your workbook contains sheets:

January
February
March'''

import pandas as pd

file_path = r"C:\Users\amita\Desktop\sales.xlsx"

sheets = pd.read_excel(
    file_path,
    sheet_name=["January", "February"]
)

print(sheets["January"])

print(sheets["February"])

   OrderID Customer  Sales
0     1001     John    500
1     1002     Mary    700
2     1003    David    400
   OrderID Customer  Sales
0     1004    Chris   1000
1     1005    Kelly    100
2     1006     Rita    500

In [60]:
#Example 3: Read Specific Sheets by Position

import pandas as pd

file_path = r"C:\Users\amita\Desktop\sales.xlsx"

sheets = pd.read_excel(
    file_path,
    sheet_name=[0, 1]
)

print("First Sheet")
print(sheets[0])

print("\nSecond Sheet")
print(sheets[1])

First Sheet
   OrderID Customer  Sales
0     1001     John    500
1     1002     Mary    700
2     1003    David    400

Second Sheet
   OrderID Customer  Sales
0     1004    Chris   1000
1     1005    Kelly    100
2     1006     Rita    500

In [61]:
#Example 4: Read One Sheet and Store in DataFrame

import pandas as pd

file_path = r"C:\Users\amita\Desktop\sales.xlsx"

jan_df = pd.read_excel(
    file_path,
    sheet_name="January"
)

print(jan_df.head())

   OrderID Customer  Sales
0     1001     John    500
1     1002     Mary    700
2     1003    David    400

In [62]:
#Example 5: Display All Sheet Names First

#Useful when you don't know sheet names.

import pandas as pd

file_path = r"C:\Users\amita\Desktop\sales.xlsx"

excel_file = pd.ExcelFile(file_path)

print(excel_file.sheet_names)

['January', 'February', 'March']

In [63]:
#Example 6: Read Every Sheet Separately
import pandas as pd

file_path = r"C:\Users\amita\Desktop\sales.xlsx"

all_sheets = pd.read_excel(
    file_path,
    sheet_name=None
)

for name, df in all_sheets.items():
    print(f"\nSheet Name: {name}")
    print(df.head())

Sheet Name: January
   OrderID Customer  Sales
0     1001     John    500
1     1002     Mary    700
2     1003    David    400

Sheet Name: February
   OrderID Customer  Sales
0     1004    Chris   1000
1     1005    Kelly    100
2     1006     Rita    500

Sheet Name: March
   OrderID Customer  Sales
0     1007    Kevin    900
1     1008    Holly    234
2     1009      Nic    253

In [64]:
# Example 7: Combine All Sheets into One DataFrame

#Very common in business reporting.

import pandas as pd

file_path = r"C:\Users\amita\Desktop\sales.xlsx"

all_sheets = pd.read_excel(
    file_path,
    sheet_name=None
)

combined_df = pd.concat(
    all_sheets.values(),
    ignore_index=True
)

print(combined_df.head())

print("\nTotal Rows:")
print(len(combined_df))

   OrderID Customer  Sales
0     1001     John    500
1     1002     Mary    700
2     1003    David    400
3     1004    Chris   1000
4     1005    Kelly    100

Total Rows:
9

In [65]:
import pandas as pd

file_path = r"C:\Users\amita\Desktop\sales.xlsx"

all_sheets = pd.read_excel(
    file_path,
    sheet_name=None
)

combined_df = pd.concat(
    all_sheets.values(),
    ignore_index=True
)

output_file = r"C:\Users\amita\Desktop\combined_sales.xlsx"

combined_df.to_excel(
    output_file,
    index=False
)

print("File saved successfully!")

File saved successfully!

In [66]:
#Example 9: Read Only Selected Columns From All Sheets
import pandas as pd

file_path = r"C:\Users\amita\Desktop\sales.xlsx"

all_sheets = pd.read_excel(
    file_path,
    sheet_name=None,
    usecols=["Customer", "Sales"]
)

for sheet_name, df in all_sheets.items():
    print(f"\n{sheet_name}")
    print(df.head())

January
  Customer  Sales
0     John    500
1     Mary    700
2    David    400

February
  Customer  Sales
0    Chris   1000
1    Kelly    100
2     Rita    500

March
  Customer  Sales
0    Kevin    900
1    Holly    234
2      Nic    253

In [67]:
#Example 10: Real-World Business Example

#Read all monthly sheets, combine them, and calculate total sales.

import pandas as pd

file_path = r"C:\Users\amita\Desktop\sales.xlsx"

all_sheets = pd.read_excel(
    file_path,
    sheet_name=None
)

combined_df = pd.concat(
    all_sheets.values(),
    ignore_index=True
)

total_sales = combined_df["Sales"].sum()

print("Total Sales:", total_sales)

combined_df.to_excel(
    r"C:\Users\amita\Desktop\annual_sales.xlsx",
    index=False
)

print("Annual report created successfully!")

Total Sales: 4587
Annual report created successfully!

In [75]:
#Skip Rows While Reading

import pandas as pd

# Path to Excel file on Desktop
file_path = r"C:\Users\amita\Desktop\sales.xlsx"

# Read Excel and skip first 2 rows
df = pd.read_excel(
    file_path,
    skiprows=2
)

In [76]:
# Display first 5 rows
print(df.head())

   1002   Mary  700
0  1003  David  400

In [77]:
# Display DataFrame information
print("\nData Information:")
print(df.info())

Data Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   1002    1 non-null      int64
 1   Mary    1 non-null      object
 2   700     1 non-null      int64
dtypes: int64(2), object(1)
memory usage: 156.0+ bytes
None

In [78]:
df.head()

   1002   Mary  700
0  1003  David  400

In [86]:
#Export Selected Data

import pandas as pd

# Read Excel file
file_path = r"C:\Users\amita\Desktop\sales.xlsx"

df = pd.read_excel(file_path)

# Check column names
print("Columns in file:")
print(df.columns)

# Filter rows where Sales > 500
high_sales = df[df["Sales"] > 500]

# Save result
output_file = r"C:\Users\amita\Desktop\high_sales.xlsx"

high_sales.to_excel(output_file, index=False)

print("File saved successfully!")

Columns in file:
Index(['OrderID', 'Customer', 'Sales'], dtype='object')
File saved successfully!