In [1]:
import pandas as pd

In [2]:
#Sample Dataset

data = {
    'Name': ['Amit', 'Rahul', None, 'Sneha', 'Amit'],
    'Age': [25, None, 30, 28, 25],
    'Salary': [50000, 60000, None, 75000, 50000]
}

df = pd.DataFrame(data)

print(df)

    Name   Age   Salary
0   Amit  25.0  50000.0
1  Rahul   NaN  60000.0
2   None  30.0      NaN
3  Sneha  28.0  75000.0
4   Amit  25.0  50000.0

In [3]:
'''🔹 1. df.isnull()
Check Missing Values

This function checks where null (missing) values exist.'''

df.isnull()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2   True  False    True
3  False  False   False
4  False  False   False

In [4]:
#🔹 Count Missing Values

df.isnull().sum()

Name      1
Age       1
Salary    1
dtype: int64

In [5]:
'''🔹 2. df.notnull()
Check Non-Missing Values

Opposite of isnull().'''

df.notnull()

    Name    Age  Salary
0   True   True    True
1   True  False    True
2  False   True   False
3   True   True    True
4   True   True    True

In [6]:
'''🔹 3. df.dropna()

Remove Missing Values

Removes rows containing null values.'''

clean_df = df.dropna()

print(clean_df)

    Name   Age   Salary
0   Amit  25.0  50000.0
3  Sneha  28.0  75000.0
4   Amit  25.0  50000.0

In [ ]:
'''🔹 Remove Columns with Missing Values
df.dropna(axis=1)
Explanation
axis=0 → Remove rows
axis=1 → Remove columns'''

In [7]:
'''🔹 4. df.fillna()
Replace Missing Values

Instead of deleting data, missing values can be filled.'''

df.fillna(0)

    Name   Age   Salary
0   Amit  25.0  50000.0
1  Rahul   0.0  60000.0
2      0  30.0      0.0
3  Sneha  28.0  75000.0
4   Amit  25.0  50000.0

In [8]:
#Fill Specific Column

df['Age'] = df['Age'].fillna(18)

print(df)

#Only missing values in the Age column are replaced.

    Name   Age   Salary
0   Amit  25.0  50000.0
1  Rahul  18.0  60000.0
2   None  30.0      NaN
3  Sneha  28.0  75000.0
4   Amit  25.0  50000.0

In [9]:
'''🔹 5. df.replace()
Replace Specific Values

Used to replace existing values.

Replace a Single Value'''

df.replace(25, 'Twenty Five')

    Name          Age   Salary
0   Amit  Twenty Five  50000.0
1  Rahul         18.0  60000.0
2   None         30.0      NaN
3  Sneha         28.0  75000.0
4   Amit  Twenty Five  50000.0

In [10]:
#Replace Multiple Values

df.replace({
    25: 'Young',
    30: 'Adult'
})

    Name    Age   Salary
0   Amit  Young  50000.0
1  Rahul   18.0  60000.0
2   None  Adult      NaN
3  Sneha   28.0  75000.0
4   Amit  Young  50000.0

In [11]:
'''🔹 6. df.rename()
Rename Columns

Useful when column names are unclear or inconsistent.'''

df.rename(columns={'Salary': 'Monthly_Salary'})

    Name   Age  Monthly_Salary
0   Amit  25.0         50000.0
1  Rahul  18.0         60000.0
2   None  30.0             NaN
3  Sneha  28.0         75000.0
4   Amit  25.0         50000.0

In [12]:
#🔹 Rename Multiple Columns

df.rename(columns={
    'Name': 'Employee_Name',
    'Age': 'Employee_Age'
})

  Employee_Name  Employee_Age   Salary
0          Amit          25.0  50000.0
1         Rahul          18.0  60000.0
2          None          30.0      NaN
3         Sneha          28.0  75000.0
4          Amit          25.0  50000.0

In [13]:
'''🔹 7. df.astype()
Change Data Types

Used to convert one data type into another.'''

df['Age'] = df['Age'].fillna(0).astype('int')

print(df.dtypes)

Name       object
Age         int64
Salary    float64
dtype: object

In [ ]:
'''🔹 Common Data Types
Data Type	Meaning
int	Integer
float	Decimal Number
object	Text/String
bool	True/False'''

In [14]:
'''🔹 8. df.drop_duplicates()
Remove Duplicate Rows

Duplicate data is very common in real datasets.'''

df.drop_duplicates()

    Name  Age   Salary
0   Amit   25  50000.0
1  Rahul   18  60000.0
2   None   30      NaN
3  Sneha   28  75000.0

In [15]:
'''🔹 Remove Duplicates Based on One Column'''

df.drop_duplicates(subset=['Name'])

    Name  Age   Salary
0   Amit   25  50000.0
1  Rahul   18  60000.0
2   None   30      NaN
3  Sneha   28  75000.0

In [16]:
'''🔹 9. df.reset_index()
Reset Index Numbers

After removing rows, indexes may become irregular.'''

new_df = df.dropna()

print(new_df)

    Name  Age   Salary
0   Amit   25  50000.0
1  Rahul   18  60000.0
3  Sneha   28  75000.0
4   Amit   25  50000.0

In [17]:
'''Reset the Index'''

new_df.reset_index()

   index   Name  Age   Salary
0      0   Amit   25  50000.0
1      1  Rahul   18  60000.0
2      3  Sneha   28  75000.0
3      4   Amit   25  50000.0

In [18]:
#Remove Old Index Column

new_df.reset_index(drop=True)

    Name  Age   Salary
0   Amit   25  50000.0
1  Rahul   18  60000.0
2  Sneha   28  75000.0
3   Amit   25  50000.0

In [20]:
#🔹 Real-World Cleaning Example

df = pd.read_csv(r"C:\Users\amita\Desktop\employees.csv")

# Remove duplicates
df = df.drop_duplicates()

# Fill missing salaries
df['Salary'] = df['Salary'].fillna(0)

# Rename columns
df = df.rename(columns={'EmpName': 'Employee_Name'})

# Reset index
df = df.reset_index(drop=True)

print(df.head())

  Employee_Name   Age   Salary Department
0          Amit  25.0  50000.0         IT
1         Rahul  30.0  60000.0         HR
2         Sneha  28.0      0.0    Finance
3         Priya   NaN  75000.0         IT
4           NaN  32.0  65000.0      Sales