In [1]:
#Step 1 — Import Pandas
import pandas as pd

In [2]:
'''Step 2 — Create or Load a DataFrame

Example DataFrame:'''

data = {
    "Name": ["Amit", "Sara", "John", "Priya", "David"],
    "Age": [28, 24, 32, 29, 35],
    "Salary": [50000, 45000, 70000, 52000, 80000],
    "Department": ["IT", "HR", "Finance", "IT", "Management"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Salary  Department
0   Amit   28   50000          IT
1   Sara   24   45000          HR
2   John   32   70000     Finance
3  Priya   29   52000          IT
4  David   35   80000  Management

In [3]:
'''1. df.head() — View First Rows

This command displays the first 5 rows of the DataFrame'''

df.head()

    Name  Age  Salary  Department
0   Amit   28   50000          IT
1   Sara   24   45000          HR
2   John   32   70000     Finance
3  Priya   29   52000          IT
4  David   35   80000  Management

In [4]:
'''Custom Number of Rows

You can specify how many rows you want.'''

df.head(2)

   Name  Age  Salary Department
0  Amit   28   50000         IT
1  Sara   24   45000         HR

In [5]:
'''2. df.tail() — View Last Rows

Shows the last 5 rows.'''

df.tail()

    Name  Age  Salary  Department
0   Amit   28   50000          IT
1   Sara   24   45000          HR
2   John   32   70000     Finance
3  Priya   29   52000          IT
4  David   35   80000  Management

In [6]:
df.tail(2)

    Name  Age  Salary  Department
3  Priya   29   52000          IT
4  David   35   80000  Management

In [7]:
'''3. df.sample() — Random Rows

Displays random rows from the dataset.'''

df.sample()

   Name  Age  Salary Department
0  Amit   28   50000         IT

In [ ]:
'''Why is sample() Important?

Very useful when working with huge datasets.

Instead of checking only top rows, random sampling helps you:

Inspect random records
Detect inconsistent values
Validate data quality
Perform quick spot-checks'''

In [9]:
'''Multiple Random Rows
Output changes every time.'''

df.sample(3)

    Name  Age  Salary  Department
1   Sara   24   45000          HR
4  David   35   80000  Management
0   Amit   28   50000          IT

In [15]:
'''4. df.shape — Dataset Dimensions

Returns number of rows and columns.'''

import pandas as pd

data = {
    "Name": ["Amit", "Sara", "John", "Priya", "David"],
    "Age": [28, 24, 32, 29, 35],
    "Salary": [50000, 45000, 70000, 52000, 80000],
    "Department": ["IT", "HR", "Finance", "IT", "Management"]
}

df = pd.DataFrame(data)

df.shape

(5, 4)

In [17]:
'''Access Individually
Number of Rows'''

import pandas as pd

data = {
"Name": ["Amit", "Sara", "John", "Priya", "David"],
    "Age": [28, 24, 32, 29, 35],
    "Salary": [50000, 45000, 70000, 52000, 80000],
    "Department": ["IT", "HR", "Finance", "IT", "Management"]
}

df = pd.DataFrame(data)

df.shape[0]

5

In [8]:
'''Number of Columns'''

import pandas as pd

data = {
    "Name": ["Amit", "Sara", "John"],
    "Age": [28, 24, 32]
}

df = pd.DataFrame(data)

df.shape[1]

2

In [9]:
'''5. df.info() — Complete Dataset Summary

One of the MOST IMPORTANT inspection commands.

What Does info() Tell You?
Information	Meaning
Total rows	Number of entries
Column names	Names of all columns
Non-null count	Missing value detection
Data types	int, float, object, etc.
Memory usage	RAM usage

Common Data Types in Pandas
Data Type	Meaning
int64	Integer numbers
float64	Decimal numbers
object	Text/String
bool	True/False
datetime64	Dates and time'''

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes

In [10]:
'''6. df.describe() — Statistical Summary

Generates statistics for numerical columns.

Meaning of Each Statistic
Statistic	Meaning
count	Number of values
mean	Average
std	Standard deviation
min	Smallest value
25%	First quartile
50%	Median
75%	Third quartile
max	Largest value'''

df.describe()

        Age
count   3.0
mean   28.0
std     4.0
min    24.0
25%    26.0
50%    28.0
75%    30.0
max    32.0

In [11]:
'''Include All Columns

By default, only numerical columns are shown.

To include text columns:'''

df.describe(include='all')

        Name   Age
count      3   3.0
unique     3   NaN
top     Amit   NaN
freq       1   NaN
mean     NaN  28.0
std      NaN   4.0
min      NaN  24.0
25%      NaN  26.0
50%      NaN  28.0
75%      NaN  30.0
max      NaN  32.0

In [18]:
'''7. df.dtypes — Check Column Data Types'''

df.dtypes

Name          object
Age            int64
Salary         int64
Department    object
dtype: object

In [19]:
'''8. df.columns — View Column Names'''

df.columns

Index(['Name', 'Age', 'Salary', 'Department'], dtype='object')

In [20]:
#Convert to List

list(df.columns)

['Name', 'Age', 'Salary', 'Department']

In [21]:
#9. df.index — View Index Information

df.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
'''What is Index?

The index is the row label system in Pandas.

Example:

0
1
2
3
4

These are index values.'''

In [22]:
'''Custom Index Example'''

df.index = ["A", "B", "C", "D", "E"]

print(df)

    Name  Age  Salary  Department
A   Amit   28   50000          IT
B   Sara   24   45000          HR
C   John   32   70000     Finance
D  Priya   29   52000          IT
E  David   35   80000  Management

In [ ]:
'''Real-World Data Inspection Workflow

Most data analysts follow this order:

df.head()

df.shape

df.info()

df.describe()

df.columns

df.dtypes

This gives a quick understanding of the dataset before cleaning or analysis.'''