In [1]:
#1. Import Pandas
import pandas as pd

In [2]:
'''2. Create Sample Dirty Dataset

We will first create a dataset with:

Missing values
Duplicate rows
Wrong data types'''

data = {
    "name": ["Amit", "Rahul", "Sneha", "Amit", None],
    "sales": [500, 700, None, 500, 900],
    "city": ["Delhi", "Mumbai", "Delhi", "Delhi", None]
}

df = pd.DataFrame(data)

print(df)

    name  sales    city
0   Amit  500.0   Delhi
1  Rahul  700.0  Mumbai
2  Sneha    NaN   Delhi
3   Amit  500.0   Delhi
4   None  900.0    None

In [ ]:
'''Understanding the Problems in This Dataset
Problem 1 — Missing Values

Some cells are empty:

None
NaN
Problem 2 — Duplicate Rows

Row 0 and Row 3 are duplicates.

Problem 3 — Wrong Data Types

Sales should ideally be integers.'''

In [ ]:
'''PART 1 — Missing Values
What are Missing Values?

Missing values are empty cells in a dataset.

Examples:

Blank Excel cells
Null database values
Missing customer information

Pandas usually shows missing values as:

NaN → Not a Number
None'''

In [ ]:
'''Check Missing Values
df.isnull()

This checks every cell and returns:

True → value is missing
False → value exists'''

In [3]:
print(df.isnull())

    name  sales   city
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False  False
4   True  False   True

In [5]:
#Count Missing Values in Each Column
print(df.isnull().sum())
'''Explanation
isnull() finds missing values
sum() counts True values

Since:

True = 1
False = 0

Pandas counts total missing values.'''

name     1
sales    1
city     1
dtype: int64

In [6]:
'''Remove Missing Values
df.dropna()

This removes rows containing missing values.'''
clean_df = df.dropna()

print(clean_df)

'''Explanation

Rows with:

Missing sales
Missing name
Missing city

were removed.'''

    name  sales    city
0   Amit  500.0   Delhi
1  Rahul  700.0  Mumbai
3   Amit  500.0   Delhi

In [ ]:
'''Important Note

dropna() can remove a lot of data.

In real projects:

Sometimes removing rows is okay
Sometimes we fill missing values instead'''

In [7]:
'''Fill Missing Values
df.fillna()

Instead of deleting rows, we can fill empty cells.'''

#Example 1 — Fill with 0
df["sales"] = df["sales"].fillna(0)

print(df)

    name  sales    city
0   Amit  500.0   Delhi
1  Rahul  700.0  Mumbai
2  Sneha    0.0   Delhi
3   Amit  500.0   Delhi
4   None  900.0    None

In [8]:
#Example 2 — Fill Text Columns
df["city"] = df["city"].fillna("Unknown")

print(df)

    name  sales     city
0   Amit  500.0    Delhi
1  Rahul  700.0   Mumbai
2  Sneha    0.0    Delhi
3   Amit  500.0    Delhi
4   None  900.0  Unknown

In [ ]:
'''Common fillna() Methods
Method	Purpose
fillna(0)	Replace missing numbers
fillna("Unknown")	Replace missing text
fillna(df.mean())	Replace with average
fillna(method="ffill")	Fill using previous row'''

In [ ]:
'''PART 2 — Remove Duplicates
What are Duplicate Rows?

Duplicate rows are repeated records.

Example:

Same customer entered twice
Same sales record repeated
System importing duplicate data

Duplicates can:

Increase totals incorrectly
Create wrong reports
Affect business decisions'''

In [9]:
#Check Duplicate Rows
print(df.duplicated())
'''Explanation

Row 3 is duplicate because:

It matches row 0'''

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [10]:
#Remove Duplicate Rows
df.drop_duplicates()
df = df.drop_duplicates()

print(df)

    name  sales     city
0   Amit  500.0    Delhi
1  Rahul  700.0   Mumbai
2  Sneha    0.0    Delhi
4   None  900.0  Unknown

In [11]:
'''Important Parameters
Keep First Duplicate (Default)'''
df.drop_duplicates(keep="first")

    name  sales     city
0   Amit  500.0    Delhi
1  Rahul  700.0   Mumbai
2  Sneha    0.0    Delhi
4   None  900.0  Unknown

In [12]:
#Keep Last Duplicate
df.drop_duplicates(keep="last")

    name  sales     city
0   Amit  500.0    Delhi
1  Rahul  700.0   Mumbai
2  Sneha    0.0    Delhi
4   None  900.0  Unknown

In [13]:
#Remove ALL Duplicates
df.drop_duplicates(keep=False)

    name  sales     city
0   Amit  500.0    Delhi
1  Rahul  700.0   Mumbai
2  Sneha    0.0    Delhi
4   None  900.0  Unknown

In [ ]:
'''PART 3 — Rename Columns
Why Rename Columns?

Real datasets often have:

Bad column names
Spaces
Short names
Inconsistent formatting

Example:

sales
Sales Amount
TOTALSALE
sales_amt

We rename columns for:

Better readability
Easier coding
Standard naming'''

In [15]:
#Rename Single Column
#df.rename()
df = df.rename(columns={"sales": "total_sales"})

print(df)

    name  total_sales     city
0   Amit        500.0    Delhi
1  Rahul        700.0   Mumbai
2  Sneha          0.0    Delhi
4   None        900.0  Unknown

In [16]:
#Rename Multiple Columns
df = df.rename(columns={
    "name": "customer_name",
    "city": "customer_city"
})

print(df)

  customer_name  total_sales customer_city
0          Amit        500.0         Delhi
1         Rahul        700.0        Mumbai
2         Sneha          0.0         Delhi
4          None        900.0       Unknown

In [ ]:
'''Best Practices for Column Names

Use:

lowercase
underscore _
meaningful names

Good:

total_sales
customer_name
order_date

Avoid:

Total Sales
TOTALSALES
x1'''

In [ ]:
'''PART 4 — Change Data Types
Why Data Types Matter

Sometimes numbers are stored as:

Text (string)

Example:

"500"

instead of:

500

This creates problems in:

Calculations
Sorting
Charts
Analysis'''

In [17]:
#Check Data Types
print(df.dtypes)

customer_name     object
total_sales      float64
customer_city     object
dtype: object

In [ ]:
'''Common Pandas Data Types
Data Type	Meaning
int64	Integer
float64	Decimal
object	Text/String
bool	True/False
datetime64	Date & Time'''

In [18]:
#Convert Data Type
#astype()
df["total_sales"] = df["total_sales"].astype(int)

print(df.dtypes)

customer_name    object
total_sales       int64
customer_city    object
dtype: object

In [ ]:
'''Important Warning

If a column contains:

Text
Missing values
Invalid numbers

Then astype(int) may produce errors.

Example:

"abc"

cannot become integer.'''

In [19]:
#FULL DATA CLEANING EXAMPLE
import pandas as pd

data = {
    "name": ["Amit", "Rahul", "Sneha", "Amit", None],
    "sales": [500, 700, None, 500, 900],
    "city": ["Delhi", "Mumbai", "Delhi", "Delhi", None]
}

df = pd.DataFrame(data)

# Check missing values
print(df.isnull().sum())

# Fill missing sales with 0
df["sales"] = df["sales"].fillna(0)

# Fill missing city
df["city"] = df["city"].fillna("Unknown")

# Remove duplicates
df = df.drop_duplicates()

# Rename column
df = df.rename(columns={"sales": "total_sales"})

# Change data type
df["total_sales"] = df["total_sales"].astype(int)

print(df)

print(df.dtypes)

name     1
sales    1
city     1
dtype: int64
    name  total_sales     city
0   Amit          500    Delhi
1  Rahul          700   Mumbai
2  Sneha            0    Delhi
4   None          900  Unknown
name           object
total_sales     int64
city           object
dtype: object

In [ ]:
'''Real-World Data Cleaning Workflow

A real analyst usually follows this order:

Step 1 — Load Data
pd.read_csv()
Step 2 — Inspect Data
df.head()
df.info()
df.describe()
Step 3 — Handle Missing Values
isnull()
fillna()
dropna()
Step 4 — Remove Duplicates
drop_duplicates()
Step 5 — Rename Columns
rename()
Step 6 — Fix Data Types
astype()
Step 7 — Begin Analysis
groupby()
pivot_table()
charts'''